### ISSUE TITLE
Hide "base" and "running" nb-conda-kernels columns by default?

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/jupyterlab-new-launcher#16]
These columns do not provide much value:
- only one kernel environment is ever marked as running (this is the default environment) as only one is used to run JupyterLab
- no environments in conda-store setup are marked as base (not sure why)

![image](https://github.com/nebari-dev/jupyterlab-new-launcher/assets/5832902/9031e31e-8043-4f36-928c-51c61ca94f12)

**Comment by kcpevey** [comment]
I'd prefer if these columns were hidden by default along with the Language since I can get that information from the "kernel" column.
