### ISSUE TITLE
"Launch Notebook" should be "Launch New Notebook"

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/jupyterlab-new-launcher#18]
### Context

The phrase "Launch Notebook" is something that users would do if they are picking from a list of notebooks. However, in the interface, its actually that users are Launching a NEW notebook in one of the environments in the list. 

The same is true for the Console dropdown

### Value and/or benefit

Less confusion for end users.

**Comment by krassowski** [comment]
Should it also be "Create _New_ Empty", or is "Create Empty" ok?

**Comment by kcpevey** [comment]
"Create New Empty" doesn't sound quite right. I think its fine to leave as "Create Empty".
