### ISSUE TITLE
Add a settings button or menu (in top right corner?)

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/jupyterlab-new-launcher#9]
We could add the cog icon in the top right corner:

![image](https://github.com/nebari-dev/jupyterlab-new-launcher/assets/5832902/18a25250-435d-4a26-9d84-9c15bf1e610f)

It could either open the existing settings section (which currently is 3-4 clicks away):

![image](https://github.com/nebari-dev/jupyterlab-new-launcher/assets/5832902/74338241-517e-4d08-a3ce-ec03d0c34150)

Or show a small menu allowing to toggle some quick settings (like whether to show starred section).

Thoughts?

**Comment by kcpevey** [comment]
I like this idea. The name may change to something more specific, but I had to actually read through the list of settings to find the settings for "New Launcher" because the name is fairly generic. This would really help jump right to it.

**Comment by andrewfulton9** [comment]
@krassowski, have you started on this, or is this something I can take a stab at?

**Comment by andrewfulton9** [comment]
@krassowski, I've been trying to figure out how to open the specific settings page via a button, and I am struggling to find a way. It looks like I can use `settingeditor:open`, but I don't think I can pass it any arguments to specify specific plugins. Am I missing something? 

If that's the case, then I think I will need to go with the second option here of adding a dropdown for key settings. Above you mentioned the setting for showing starred section. What other sections do you think should be included here?

**Comment by krassowski** [comment]
>  It looks like I can use settingeditor:open, but I don't think I can pass it any arguments to specify specific plugins.

Something like this should work:

```js
app.commands.execute('settingeditor:open', {
  query: 'New Launcher'
})
```

> If that's the case, then I think I will need to go with the second option here of adding a dropdown for key settings

I think that would be best in either case - I think having quick settings may make them more discoverable.

>  What other sections do you think should be included here?

Including a toggle for `searchAllSections` might be valuable too.

Maybe something like:

```
✓ Search in All Sections
✓ Show Starred Section
  Open Settings
```

We can add more items later. I think you use `Menu` class and add commands to it (which will need to be created).

**Comment by krassowski** [comment]
Any updates @andrewfulton9?

**Comment by andrewfulton9** [comment]
@krassowski, it's coming along. I've added commands for the new options, and added the commands to a Menu object. I am currently working on displaying the menu in a popup opened from a settings icon.
